name: PyPy Release
on:
  release:
    types: [published, edited]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3

      - name: tag name
        run: echo $GITHUB_REF_NAME

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
       
      - name: Config Poetry
        working-directory: ./src
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          python -m pip install --upgrade pip
          poetry install

      - name: Build
        working-directory: ./src
        run: |
          poetry build

      - name: publish
        working-directory: ./src
        run: |
          poetry publish -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}